uuid = "c21ca1c6-76bc-11ed-088c-e9958cb3e20c"
seed = 1234
showprogress = false

[shape]
ndims = 3
size = 12

    [shape.storage]
    data_dir = "data"
    checkpoint = "checkpoint.txt"
    tags = []

[sample]
nburns = 10000
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 10.0
step = -0.01
stop = 0.1
