uuid = "c1de2ff4-76bc-11ed-0035-c5f847441425"
seed = 1234
showprogress = false

[shape]
ndims = 3
size = 4

    [shape.storage]
    data_dir = "data"
    checkpoint = "checkpoint.txt"
    tags = []

[sample]
nburns = 10000
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 10.0
step = -0.01
stop = 0.1
