uuid = "c22f8dfe-76bc-11ed-2f12-3de5e1894271"
seed = 1234
showprogress = false

[shape]
ndims = 4
size = 16

    [shape.storage]
    data_dir = "data"
    checkpoint = "checkpoint.txt"
    tags = []

[sample]
nburns = 10000
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 10.0
step = -0.01
stop = 0.1
