uuid = "c243c3f0-76bc-11ed-0253-e93967fba09c"
seed = 1234
showprogress = false

[shape]
ndims = 6
size = 4

    [shape.storage]
    data_dir = "data"
    checkpoint = "checkpoint.txt"
    tags = []

[sample]
nburns = 10000
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 10.0
step = -0.01
stop = 0.1
