uuid = "c24440e6-76bc-11ed-2370-6dd4dbc3ef1e"
seed = 1234
showprogress = false

[shape]
ndims = 6
size = 6

    [shape.storage]
    data_dir = "data"
    checkpoint = "checkpoint.txt"
    tags = []

[sample]
nburns = 10000
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 10.0
step = -0.01
stop = 0.1
