uuid = "c244bb5c-76bc-11ed-326e-2fc06d770434"
seed = 1234
showprogress = false

[shape]
ndims = 6
size = 8

    [shape.storage]
    data_dir = "data"
    checkpoint = "checkpoint.txt"
    tags = []

[sample]
nburns = 10000
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 10.0
step = -0.01
stop = 0.1
