seed = 6386046511793212336

[shape]
ndims = 3
size = 4

[shape.storage]
data_dir = "data"
tags = []

[sample]
nburns = 10_000
nsamples = 500
nthrows = 10
observables = ["E", "E^2", "M"]

[temperature]
start = 4.6
step = 0.01
stop = 0.1
