njobs = 1
seed = 1234
walltime = "3-00:00:00"

[shape]
ndims = 4
p = 3
size = 3

[storage]
path = "data"
tags = []

[sample]
nrepeat = 2
nsamples = 200_000
nthrows = 10
observables = ["E", "E^2", "M", "M^2", "accept_rate"]

    [sample.option]
    nburns = 5000
    order = "random"
    [sample.option.gauge]
    steps = 5

[fields]
start = 0.2
step = 0.01
stop = 0.2

[temperatures]
start = 1.5
step = -0.02
stop = 0.05

[checkpoint.temperatures]
start = 1.5
step = -0.02
stop = 0.05

[checkpoint.fields]
start = 0.2
step = 0.01
stop = 0.2
