uuid = "93cf78b4-7a6f-11ed-37ba-0945dd5ba9f5"
repeat = 5

[shape]
ndims = 3
size = 4

[shape.storage]
data_dir = "data"
checkpoint = "checkpoint.txt"
tags = []

[sample]
nsamples = 500000
nthrows = 10
observables = ["E", "E^2"]

[temperature]
start = 2.5
step = -0.01
stop = 0.1
