njobs = 800
seed = 1234

[shape]
ndims = 3
p = 3
size = 4

[storage]
path = "data"
tags = ["test"]

[sample]
nrepeat = 200
nsamples = 5000
nthrows = 10
observables = ["E", "E^2", "M", "M^2"]

    [sample.option]
    nburns = 1000
    order = "random"

[fields]
start = 0.0
step = 0.01
stop = 1.0

[temperatures]
start = 10.0
step = -0.05
stop = 0.05
