njobs = 800
seed = 1234

[shape]
ndims = 3
p = 3
size = 4

[storage]
path = "data"
tags = ["test"]

[sample]
nrepeat = 10
nsamples = 1000
nthrows = 1000
observables = ["E", "E^2"]

    [sample.option]
    nburns = 1000
    order = "random"

[fields]
start = 0.0
step = 0.01
stop = 1.0

[temperatures]
start = 10.0
step = -0.1
stop = 0.1
